### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by at15** [at15/jepsen#1]
Ceph  https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/16.04/base/Dockerfile

Jepsen https://github.com/jepsen-io/jepsen/tree/master/docker/node

**Comment by at15** [comment]
btw: jepsen also offer db automation https://github.com/jepsen-io/jepsen/blob/master/doc/db.md

**Comment by at15** [comment]
after change the base image to ubuntu 16.04 got the following error 

```
Package sysvinit is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  systemd-sysv upstart-sysv upstart sysvinit-utils

Package sysvinit-core is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  systemd-sysv upstart-sysv

E: Package 'sysvinit-core' has no installation candidate
E: Package 'sysvinit' has no installation candidate
ERROR: Service 'node' failed to build: The command '/bin/sh -c rm /etc/apt/apt.conf.d/docker-clean && apt-get update && apt-get install -y sudo net-tools wget sysvinit-core sysvinit sysvinit-utils curl vim man faketime unzip iptables iputils-ping logrotate && apt-get remove -y --purge --auto-remove systemd' returned a non-zero code: 100
```

the problem is for sysvinit package 

```
E: Package 'sysvinit-core' has no installation candidate
E: Package 'sysvinit' has no installation candidate
```

**Comment by at15** [comment]
after change to ubuntu as base image got the folllowing 

```
[INFO] Running `docker-compose up`
[INFO] Please run `docker exec -it jepsen-control bash` in another terminal to proceed
Recreating jepsen-n2
Recreating jepsen-n4
Recreating jepsen-node
Recreating jepsen-n5
Recreating jepsen-n3
Recreating jepsen-n1
Recreating jepsen-control
Attaching to jepsen-n2, jepsen-n4, jepsen-node, jepsen-n5, jepsen-n3, jepsen-n1, jepsen-control
jepsen-n2 exited with code 0
jepsen-n4 exited with code 0
jepsen-n3 exited with code 0
jepsen-node exited with code 0
jepsen-n5 exited with code 0
jepsen-n1 exited with code 0
jepsen-control | getaddrinfo n1: Name or service not known
jepsen-control | getaddrinfo n2: Name or service not known
jepsen-control | getaddrinfo n3: Name or service not known
jepsen-control | getaddrinfo n4: Name or service not known
jepsen-control | getaddrinfo n5: Name or service not known
```

**Comment by at15** [comment]
node exit because in the base image https://github.com/tutumcloud/tutum-debian/blob/master/run.sh have exec /usr/sbin/sshd -D

**Comment by at15** [comment]
lol auth failed 

```
ERROR [2016-10-29 19:00:41,999] main - jepsen.mongodb.runner Oh jeez, I'm sorry, Jepsen broke. Here's why:
com.jcraft.jsch.JSchException: Auth fail
    at com.jcraft.jsch.Session.connect(Session.java:512) ~[jsch-0.1.53.jar:na]
    at com.jcraft.jsch.Session.connect(Session.java:183) ~[jsch-0.1.53.jar:na]
    at clj_ssh.ssh$fn__3682.invokeStatic(ssh.clj:118) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at clj_ssh.ssh$fn__3682.invoke(ssh.clj:115) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at clj_ssh.ssh.protocols$fn__3640$G__3607__3649.invoke(protocols.clj:4) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at clj_ssh.ssh$connect.invokeStatic(ssh.clj:401) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at clj_ssh.ssh$connect.invoke(ssh.clj:397) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at jepsen.control$clj_ssh_session.invokeStatic(control.clj:241) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at jepsen.control$clj_ssh_session.invoke(control.clj:233) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at jepsen.control$session$fn__4065.invoke(control.clj:253) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at jepsen.reconnect$open_BANG_$fn__3960.invoke(reconnect.clj:59) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at jepsen.reconnect$open_BANG_.invokeStatic(reconnect.clj:57) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at jepsen.reconnect$open_BANG_.invoke(reconnect.clj:54) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at jepsen.control$session.invokeStatic(control.clj:252) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at jepsen.control$session.invoke(control.clj:249) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.8.0.jar:na]
    at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.8.0.jar:na]
    at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
    at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881) ~[clojure-1.8.0.jar:na]
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881) ~[clojure-1.8.0.jar:na]
    at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.8.0.jar:na]
    at clojure.core$apply.invokeStatic(core.clj:650) ~[clojure-1.8.0.jar:na]
    at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911) ~[clojure-1.8.0.jar:na]
    at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.8.0.jar:na]
    at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
    at clojure.core$apply.invoke(core.clj:641) ~[clojure-1.8.0.jar:na]
    at jepsen.core$fcatch$wrapper__5867.doInvoke(core.clj:56) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.8.0.jar:na]
    at jepsen.util$real_pmap$launcher__3244$fn__3245.invoke(util.clj:28) ~[jepsen-0.1.3-SNAPSHOT.jar:na]
    at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[clojure-1.8.0.jar:na]
    at clojure.lang.AFn.call(AFn.java:18) ~[clojure-1.8.0.jar:na]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
```

**Comment by at15** [comment]
the problem is `docker exec -it jepsen-control bash` I can ssh into `jespen -n1` etc, but jsch still fail, maybe it's the wrong key position?

no, wrong sshd_config using sed, different in ubuntu and debian

**Comment by at15** [comment]
after switching to ceph/daemon, it just exit, use -D got 

```
[0000] Corrupted prefix: []                         
DEBU[0000] [hijack] End of stdout 
```

FIX: update entrypoint to empty, otherwise the command executed is always wrong.
